import { Recipe } from "@/presentation/recipes/types";

export const ALL_RECIPES: Omit<Recipe, "matchedIngredients">[] = [
    {
        id: "1",
        name: "Omelette de espinacas",
        emoji: "🍳",
        time: "10 min",
        difficulty: "Fácil",
        ingredients: ["huevos", "espinacas", "queso", "sal", "aceite"],
        steps: [
            "Bate 2-3 huevos con sal y pimienta.",
            "Calienta aceite en una sartén a fuego medio.",
            "Agrega las espinacas y saltea 1 minuto.",
            "Vierte los huevos y cocina hasta que cuajen.",
            "Agrega el queso rallado, dobla y sirve.",
        ],
    },
    {
        id: "2",
        name: "Arroz con pollo",
        emoji: "🍗",
        time: "35 min",
        difficulty: "Medio",
        ingredients: ["arroz", "pollo", "zanahorias", "sal", "aceite"],
        steps: [
            "Corta el pollo en trozos y sazona con sal.",
            "Dora el pollo en aceite caliente, 5 min por lado.",
            "Agrega las zanahorias cortadas en cubos.",
            "Incorpora el arroz lavado y cubre con agua (doble volumen).",
            "Cocina a fuego bajo 20 minutos con tapa.",
        ],
    },
    {
        id: "3",
        name: "Batido verde energético",
        emoji: "🥤",
        time: "5 min",
        difficulty: "Fácil",
        ingredients: ["espinacas", "manzanas", "leche", "yogur"],
        steps: [
            "Lava las espinacas y la manzana.",
            "Corta la manzana en trozos (sin semillas).",
            "Coloca todos los ingredientes en la licuadora.",
            "Licúa por 1 minuto hasta obtener una mezcla homogénea.",
            "Sirve frío y disfruta.",
        ],
    },
    {
        id: "4",
        name: "Ensalada de zanahorias",
        emoji: "🥗",
        time: "10 min",
        difficulty: "Fácil",
        ingredients: ["zanahorias", "manzanas", "yogur", "sal"],
        steps: [
            "Ralla las zanahorias y corta la manzana en cubos.",
            "Mezcla en un bowl con el yogur.",
            "Sazona con sal y unas gotas de limón.",
            "Refrigera 10 minutos antes de servir.",
        ],
    },
    {
        id: "5",
        name: "Yogur con frutas",
        emoji: "🍓",
        time: "3 min",
        difficulty: "Fácil",
        ingredients: ["yogur", "manzanas", "frutas"],
        steps: [
            "Corta las frutas en trozos pequeños.",
            "Coloca el yogur en un bowl.",
            "Agrega las frutas encima.",
            "Opcional: añade granola o miel.",
        ],
    },
    {
        id: "6",
        name: "Sopa de verduras",
        emoji: "🍲",
        time: "25 min",
        difficulty: "Fácil",
        ingredients: ["zanahorias", "espinacas", "sal", "aceite"],
        steps: [
            "Corta las zanahorias en rodajas.",
            "Calienta aceite and sofríe las verduras 3 minutos.",
            "Agrega 4 tazas de agua y sal.",
            "Cocina 15 minutos a fuego medio.",
            "Agrega las espinacas al final, cocina 2 min más.",
        ],
    },
    {
        id: "7",
        name: "Leche con avena",
        emoji: "🥣",
        time: "5 min",
        difficulty: "Fácil",
        ingredients: ["leche", "arroz", "granos"],
        steps: [
            "Calienta la leche en una olla a fuego bajo.",
            "Agrega avena o arroz cocido.",
            "Revuelve constantemente por 3 minutos.",
            "Endulza al gusto y sirve caliente.",
        ],
    },
    {
        id: "8",
        name: "Pollo al horno con verduras",
        emoji: "🍖",
        time: "45 min",
        difficulty: "Medio",
        ingredients: ["pollo", "zanahorias", "sal", "aceite"],
        steps: [
            "Precalienta el horno a 200°C.",
            "Sazona el pollo con sal, pimienta y aceite.",
            "Coloca las zanahorias alrededor.",
            "Hornea 40 minutos hasta dorar.",
            "Deja reposar 5 minutos antes de servir.",
        ],
    },
];
